### PR TITLE
config: fix HNC config templating

### PR DESCRIPTION
**Pull request by OlleLarsson**
> [!warning]
> **This is a public repository, ensure not to disclose:**
>
> - [x] personal data beyond what is necessary for interacting with this pull request, nor
> - [x] business confidential information, such as customer names.

### What kind of PR is this?

**Required**: Mark one of the following that is applicable:

- [ ] kind/feature       
- [ ] kind/improvement   
- [ ] kind/deprecation   
- [ ] kind/documentation 
- [ ] kind/clean-up      
- [x] kind/bug           
- [ ] kind/other         

*Optional*: Mark one or more of the following that are applicable:

> [!important]
> Breaking changes should be marked `kind/admin-change` or `kind/dev-change` depending on type
> Critical security fixes should be marked with `kind/security`

- [ ] kind/admin-change 
- [ ] kind/dev-change   
- [ ] kind/security     
- [ ] [kind/adr]()      

### What does this PR do / why do we need this PR?

Now unpropagatedAnnotations and managedNamespaceAnnotations can be specified as lists as originally intended.

...

#### Information to reviewers

Values set
```yaml
hnc:
  managedNamespaceAnnotations:
    - asd
    - hej
```

Before:
```diff
+             - --managed-namespace-annotation=asd hej
```

Now:

```diff
+             - --managed-namespace-annotation=asd
+             - --managed-namespace-annotation=hej
```

#### Checklist

- [x] Proper commit message prefix on all commits
  
- Change checks:
  - [x] The change is transparent
  - [ ] The change is disruptive
  - [ ] The change requires no migration steps
  - [ ] The change requires migration steps
  - [ ] The change upgrades CRDs
  - [ ] The change updates the config *and* the schema
- Documentation checks:
  - [x] The [public documentation](https://github.com/elastisys/compliantkubernetes) required no updates
  - [ ] The [public documentation](https://github.com/elastisys/compliantkubernetes) required an update - [link to change](set-me\)
- Metrics checks:
  - [ ] The metrics are still exposed and present in Grafana after the change
  - [x] The metrics names didn't change (Grafana dashboards and Prometheus alerts are not affected)
  - [ ] The metrics names did change (Grafana dashboards and Prometheus alerts were fixed)
- Logs checks:
  - [ ] The logs do not show any errors after the change
- Pod Security Policy checks:
  - [ ] Any changed pod is covered by Pod Security Admission
  - [ ] Any changed pod is covered by Gatekeeper Pod Security Policies
  - [ ] The change does not cause any pods to be blocked by Pod Security Admission or Policies
- Network Policy checks:
  - [ ] Any changed pod is covered by Network Policies
  - [ ] The change does not cause any dropped packets in the `NetworkPolicy Dashboard`
- Audit checks:
  - [ ] The change does not cause any unnecessary Kubernetes audit events
  - [ ] The change requires changes to Kubernetes audit policy
- Falco checks:
  - [ ] The change does not cause any alerts to be generated by Falco
- Bug checks:
  - [ ] The bug fix is covered by regression tests

### CODE REVIEW

**Review by robinAwallace — APPROVED** [review]

**Comment by robinAwallace** [comment]
Would it be possible to add a test for this? @simonklb you maybe know how and where to add it?

**Review by anders-elastisys — APPROVED** [review]

**Comment by simonklb** [comment]
> Would it be possible to add a test for this? @simonklb you maybe know how and where to add it?

Yes! I don't think we have any tests that does this currently but it would be nice to introduce tests that verifies that our config renders the expected manifests.

You could probably take inspiration from https://github.com/elastisys/compliantkubernetes-apps/blob/e9a679fa7ee04e5236fe0a69c25cfb94a21cafc7/tests/unit/general/chart-lint.bats#L29

**Review by viktor-f — APPROVED** [review]

**Comment by OlleLarsson** [comment]
> > Would it be possible to add a test for this? @simonklb you maybe know how and where to add it?
> 
> Yes! I don't think we have any tests that does this currently but it would be nice to introduce tests that verifies that our config renders the expected manifests.
> 
> You could probably take inspiration from
> 
> https://github.com/elastisys/compliantkubernetes-apps/blob/e9a679fa7ee04e5236fe0a69c25cfb94a21cafc7/tests/unit/general/chart-lint.bats#L29

Do you think that I should try to find the time to add tests for this?
I'm not too familiar with bats and I'm therefore a bit unsure of how big of a task it would be to add the tests :sweat_smile:

**Comment by simonklb** [comment]
> > > Would it be possible to add a test for this? @simonklb you maybe know how and where to add it?
> > 
> > 
> > Yes! I don't think we have any tests that does this currently but it would be nice to introduce tests that verifies that our config renders the expected manifests.
> > You could probably take inspiration from
> > https://github.com/elastisys/compliantkubernetes-apps/blob/e9a679fa7ee04e5236fe0a69c25cfb94a21cafc7/tests/unit/general/chart-lint.bats#L29
> 
> Do you think that I should try to find the time to add tests for this? I'm not too familiar with bats and I'm therefore a bit unsure of how big of a task it would be to add the tests 😅

Completely up to you! It brings up a good question though, maybe we should add one or two extra story points for testing purposes. @elastisys/scrum-masters ?

**Review by Pavan-Gunda — APPROVED** [review]

**Pull request merged**
