### PR TITLE
bin: Update dependencies

### PR DESCRIPTION
**Pull request by aarnq**
> [!warning]
> **This is public repository, ensure not to disclose:**
> - [x] personal data beyond what is necessary for interacting with this pull request
> - [x] business confidential information, such as customer names

### What kind of PR is this?

**Required**: Mark one of the following that is applicable:

- [ ] kind/feature       
- [x] kind/improvement   
- [ ] kind/deprecation   
- [ ] kind/documentation 
- [ ] kind/clean-up      
- [ ] kind/bug           
- [ ] kind/other         

*Optional*: Mark one or more of the following that are applicable:

> [!important]
> Breaking changes should be marked `kind/admin-change` or `kind/dev-change` depending on type
> Critical security fixes should be marked with `kind/security`

- [x] kind/admin-change  
- [ ] kind/dev-change    
- [ ] kind/security      
- [ ] [kind/adr]()       

### Platform Administrator notice

Local requirements have been updated, run `./bin/ck8s install-requirements` to update them.

### What does this PR do / why do we need this PR?

Updates local requirements.

This enables helmfile value templates to use helper templates (must be suffixed with `.tpl` and placed in the same directory as your value template) that can used with `include` exactly as it is used in helm.

#### Additional information to reviewers

Save for some issues with auto detection of file types (for something that wasn't supported type at all) I have not seen any issues with this change.

#### Checklist

- [x] Proper commit message prefix on all commits
  
- Change checks:
  - [x] The change is transparent
  - [ ] The change is disruptive
  - [ ] The change requires no migration steps
  - [x] The change requires migration steps
- Metrics checks:
  - [ ] The metrics are still exposed and present in Grafana after the change
  - [ ] The metrics names didn't change (Grafana dashboards and Prometheus alerts are not affected)
  - [ ] The metrics names did change (Grafana dashboards and Prometheus alerts were fixed)
- Logs checks:
  - [ ] The logs do not show any errors after the change
- Network Policy checks:
  - [ ] Any changed pod is covered by Network Policies
  - [ ] The change does not cause any dropped packages in the `NetworkPolicy Dashboard`
- Pod Security Policy checks:
  - [ ] Any changed pod is covered by Pod Security Admission
  - [ ] Any changed pod is covered by Gatekeeper Pod Security Policies
  - [ ] The change does not cause any pods to be blocked by Pod Security Admission or Policies
- Falco checks:
  - [ ] The change does not cause any alerts to be generated by Falco
- Audit checks:
  - [ ] The change does not cause any unnecessary Kubernetes audit events
  - [ ] The change requires changes to Kubernetes audit policy
- Bug checks:
  - [ ] The bug fix is covered by regression tests

### CODE REVIEW

**Review by crssnd — APPROVED** [review]

**Review by davidumea — APPROVED** [review]

**Review by robinAwallace — APPROVED** [review]

**Comment by aarnq** [comment]
> It would be nice to have some kind of policy around how to deal with upgrading dependencies. I realize that it's not as critical as bumping the version of some of the applications running inside the clusters but it's not completely harmless. For example, why did Helm secrets bump their major version?
> 
> Should we enforce some kind of summary of the biggest changes since the current version or should we rely on tests and QA?

We could extend the PR template to include that such things should be documented.
As for this change helm secrets changed and removed some cli commands and arguments, and changed the name for drivers to backends.
This isn't really something that impacts us as we rely on helmfile to integrate with helm-secrets (and we've been really behind on the version that they list as supported).

**Comment by aarnq** [comment]
I'll hold this for a while, I've seen issues installing fresh charts that contains CRs of their own CRDs.

**Comment by simonklb** [comment]
> I'll hold this for a while, I've seen issues installing fresh charts that contains CRs of their own CRDs.

You could probably send separate PRs for some of the upgrades. Maybe `yq` and the sync of `kubectl` in the pipeline could be two separate PRs that could be merged on their own?

**Comment by aarnq** [comment]
> > I'll hold this for a while, I've seen issues installing fresh charts that contains CRs of their own CRDs.
> 
> You could probably send separate PRs for some of the upgrades. Maybe `yq` and the sync of `kubectl` in the pipeline could be two separate PRs that could be merged on their own?

Downgraded one minor version as this one seems to keep the previous behaviour.
Do you still feel like this should be split up or is it ok having it as it is?

**Comment by simonklb** [comment]
> > > I'll hold this for a while, I've seen issues installing fresh charts that contains CRs of their own CRDs.
> > 
> > 
> > You could probably send separate PRs for some of the upgrades. Maybe `yq` and the sync of `kubectl` in the pipeline could be two separate PRs that could be merged on their own?
> 
> Downgraded one minor version as this one seems to keep the previous behaviour. Do you still feel like this should be split up or is it ok having it as it is?

I think we can merge this but the good thing about making things more atomic is that it makes git bisect and revert more useful in case something starts bugging out.

**Pull request merged**
