### PR TITLE
Aarnq/charts script

### LINKED ISSUE #1639: Create upstream chart manager script
**Is your feature request related to a problem? Please describe.**

Check, managing, and upgrading upstream charts is right now a fully manual process, and that means it takes some time. Which we can improve with some automation.

**Describe the solution you'd like**

Script that can manage upstream charts and improve the contributor experience, while opening up ways to automatically check for updates, check for changes, and manage versions.

**Definition of done:**

- [ ] Script that implements the features above.

### PR DESCRIPTION
**Pull request by aarnq**
**What this PR does / why we need it**:

Fixes #1639 

This is a work in progress to improve the experience of working with upstream charts.

It adds an index (a helmfile state file) of the upstream charts with their repositories so one can list (check for updates), pull (update), diff (on different aspects of any chart version in the repo), and verify the checksum of the chart to ensure it hasn't been tampered with.

The same index is used as reference for the rest of the state files so they are in sync. And the script will only pull the version stated in the index. One would need to update it to change the requested version.

I also moved upstream charts to highlight which repository they come from.

**Special notes for reviewer**:

I also have the idea of using packed charts, extracting only the values file to have as a reference and for reviewer to have as a baseline for changes.
But I don't know if that would degrade the review process too much. Though the way I see it it help to simplify the review process by allowing us to focus only on our integration of components, but it would make it more involved for a reviewer to actually inspect the templates/manifests as that would only be able to be done locally.

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
  - [x] is completely transparent, will not impact the workload in any way.
  - [ ] requires running a migration script.
  - [ ] will create noticeable cluster degradation.
        E.g. logs or metrics are not being collected or Kubernetes API server
        will not be responding while upgrading.
  - [ ] requires draining and/or replacing nodes.
  - [ ] will change any APIs.
        E.g. removes or changes any CK8S config options or Kubernetes APIs.
  - [ ] will break the cluster.
        I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
  - [x] I upgraded no Chart.
  - [ ] I upgraded a Chart and determined that no migration steps are needed.
  - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

### CODE REVIEW

**Review by crssnd — APPROVED** [review]
did some quick tests and it looks good, but I would skip the packed charts, for now

**Review by viktor-f — APPROVED** [review]
Tested some things and it works well

**Comment by aarnq** [comment]
Will merge after all current chart upgrades are in.

**Comment by aarnq** [comment]
I realised that I didn't need to tie the format of the index to helmfile, and the templating to generate release templates is *much* simpler than the recursive load.

**Review by crssnd — APPROVED** [review]

**Comment by aarnq** [comment]
Charts failing verification:
- aquasecurity/trivy-operator
- goharbor/harbor
- kubernetes-ingress-nginx/ingress-nginx
- prometheus-community/kube-prometheus-stack

I will let them be and it will be resolved next time we upgrade them with this new method.

**Pull request merged**
