### PR TITLE
Add resource requests

### LINKED ISSUE #580: Starboard: Unable to scan images from private container registries (harbor)
**Describe the bug**
Starbord cannot scan images in private container registries.
Should it be able to do that?
Probably, otherwise the aggregated vulnerability report will be skewed. (and no having the image scanned in Harbor is not the same thing imo.)
```
{"level":"error","ts":1629790832.3551853,"logger":"reconciler.vulnerabilityreport","msg":"Scan job container","job":"monitoring/scan-vulnerabilityreport-79997bb447","container":"hej","status.reason":"Error","status.message":"2021-08-24T07:40:30.947Z\t\u001b[31mFATAL\u001b[0m\tunable to initialize a scanner: unable to initialize a docker scanner: 3 errors occurred:\n\t* unable to inspect the image (harbor.net/hej/:master-fc7b7b3a): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* GET https://harbor.net/v2/hej/manifests/master-fc7b7b3a: UNAUTHORIZED: unauthorized to access repository: hej, action: pull: unauthorized to access repository: hej, action: pull\n\n\n","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).processFailedScanJob\n\t/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:417\ngithub.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).reconcileJobs.func1\n\t/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:325\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/reconcile/reconcile.go:102\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99"}
```

**To Reproduce**
- Install starboard
- Use image from private registry
- Observer error

**Expected behavior**

**Screenshots**

**Version (add all relevant versions):**
v0.16.0

**Additional context**

### PR DESCRIPTION
**Pull request by crssnd**
**What this PR does / why we need it**: added resources requests for apps

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #580 and #545 

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:
- the values for the resource requests and limits are based on what I observed on 3 prod cluster;
- the remaining containers without resource requests are rook-ceph (I will fix them from the kubespray repo);
- I didn't find a solution for adding resource requests to kube-proxy, kube-apiserver, kube-scheduler and kube-controller. The manifests from kubernetes do not contain this fields and cannot be added or costumized via kubeadm.
- sc:
sc_cluster_size

- wc:
wc_cluster_resources

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [x] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [ ] I upgraded no Chart.
    - [x] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

### CODE REVIEW

**Review by Xartos — APPROVED** [review]
LGTM!

**Review by OlleLarsson — COMMENTED** [review]
Didn't go through everything, but add some notes to the WIP-changelog that this might cause some disruptions as a lot of containers got resource requests (nginx, kibana etc) that will imply pod restarts.

**Comment by viktor-f** [comment]
This looks very nice!
Are these numbers very close to the actual usage you have seen, or does this include some slack in case a cluster would need more resources for an app or the usage sometimes spikes a bit?

**Review by robinelastisys — APPROVED** [review]

**Comment by crssnd** [comment]
> This looks very nice!
> Are these numbers very close to the actual usage you have seen, or does this include some slack in case a cluster would need more resources for an app or the usage sometimes spikes a bit?

@OlleLarsson I added some warnings :)

**Comment by crssnd** [comment]
> This looks very nice!
> Are these numbers very close to the actual usage you have seen, or does this include some slack in case a cluster would need more resources for an app or the usage sometimes spikes a bit?

@viktor-f  I updated the numbers with what I noticed on the prod clusters
requests = avg usage on the last 7 days
limits = I doubled the requests value or I put a value to cover the observed spikes

**Review by viktor-f — APPROVED** [review]

**Pull request merged**
