### PR TITLE
apps wc: Make alertmanager an operator namespace

### LINKED ISSUE #686: 1 User alertmanager does not pass strictest safeguards
**Describe the bug**

We started adding various [safeguards](https://elastisys.io/compliantkubernetes/user-guide/safeguards/). They seem to mostly work, except user-alertmanager cannot start (see error message below).

**To Reproduce**

Install apps using the following configuration:
```yaml
opa:
  imageRegistry:
    enforcement: deny
    URL:
      - harbor.ckdemo.a1ck.io
      - quay.io/jetstack/cert-manager-acmesolver
  networkPolicies:
    enforcement: deny
  resourceRequests:
    enforcement: deny
```

**Expected behavior**

User alertmanager starts without error.

**Screenshots**
```
level=error ts=2021-11-16T14:18:23.957111317Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"alertmanager/alertmanager\" failed: failed to create statefulset: admission webhook \"validation.gatekeeper.sh\" denied the request: [denied by require-harbor-repo] container \"alertmanager\" has an invalid image repo \"quay.io/prometheus/alertmanager:v0.21.0\", allowed repos are [\"harbor.ckdemo.a1ck.io\", \"quay.io/jetstack/cert-manager-acmesolver\"]\n[denied by require-harbor-repo] container \"config-reloader\" has an invalid image repo \"quay.io/prometheus-operator/prometheus-config-reloader:v0.48.1\", allowed repos are [\"harbor.ckdemo.a1ck.io\", \"quay.io/jetstack/cert-manager-acmesolver\"]\n[denied by require-networkpolicy] No matching networkpolicy found\n[denied by require-resource-requests] Container \"alertmanager\" has no cpu request"
```

**Version (add all relevant versions):**
 - Compliant Kubernetes apps v0.18.0

**Additional context**

I see two solutions to this problem.
1. We disable Gatekeeper for the alertmanager namespace.
2. We document what repos to allowlist (as we did for the acme resolver) and add requests to user-alertmanager

### PR DESCRIPTION
**Pull request by aarnq**
**What this PR does / why we need it**:
Makes the user alertmanager namespace and operator namespace.
Also moves the chart out of `examples/` per #673.

**Which issue this PR fixes**:
Fixes #686.

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [x] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [x] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [x] I upgraded no Chart.
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

### CODE REVIEW

**Comment by crssnd** [comment]
can we install alertmanager via the kube-prometheus-stack-wc chart?

**Comment by aarnq** [comment]
> can we install alertmanager via the kube-prometheus-stack-wc chart?

Currently we can't, I think. Since that would deploy it in the `monitoring` namespace, which we probably don't want to expose in any way if we can avoid it.

**Comment by robinelastisys** [comment]
Great work! Just want to make sure - did this follow @crssnd's advice?:
_After thinking about it a bit, I think it's better to add the owner: operator label.

We should also remove the alertmanager namespace from the "user namespaces" and add a minimal RBAC, enough for the user to change alertmanager configuration and inspect alertmanager state._

**Comment by aarnq** [comment]
> Great work! Just want to make sure - did this follow @cristiklein advice?

Yes, that is what this change does.
Though I'm going to rework it a bit to move the RBAC from user-rbac into user-alertmanager to simplify the migration steps and make it contained within a single chart.

**Review by crssnd — APPROVED** [review]

**Review by OlleLarsson — APPROVED** [review]

**Pull request merged**
