### PR TITLE
bin: Fix check for bash array in team.bash

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:
The check was for a normal bash environment variable, but it is actually an array.

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: none

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [x] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

### CODE REVIEW

**Review by viktor-f — APPROVED** [review]

**Review by OlleLarsson — APPROVED** [review]
I'm not 100% sure what this changes.
Do you have any examples of what didn't work that now does?

**Comment by lentzi90** [comment]
Basically the bash expansion doesn't work with an array so I got `Missing secrets` when I tried running `team-add`. I came up with this that seems to work. Here is an example of how it works:

```console
❯ declare -A secrets
❯ secrets["a"]="something"
❯ secrets["b"]="somethingelse"
❯ echo "secrets: ${secrets[@]}"
❯ : "${secrets:?Missing secrets}"
bash: secrets: Missing secrets
❯ : "${secrets[@]:?Missing secrets array}"
❯ # Try an empty array to see if we catch it
❯ declare -A empty_array
❯ echo "empty_array: ${empty_array[@]}"
empty_array:
❯ : "${empty_array:?Missing empty_array}"
bash: empty_array: Missing empty_array
❯ : "${empty_array[@]:?Missing empty_array array}"
bash: empty_array[@]: Missing empty_array array
```

**Review by simonklb — APPROVED** [review]
I don't remember adding this? Why is the check necessary? Something must have gone horribly wrong if the secrets variable is unset. :smile: In any case, LGTM!

Really curious how this hasn't been hit before though? Is the command not being used?

**Comment by lentzi90** [comment]
I guess it is not being used enough at least :joy: And honestly, I don't get why the check is necessary. :slightly_frowning_face:

**Pull request merged**
