### PR TITLE
Ingress-nginx upgrade

### LINKED ISSUE #805: [5] Upgrade ingress-nginx to v1.0
**What Chart should be upgraded?**
upstream / ingress-nginx

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

Need to upgrade this for it to support APIs on K8s v1.22 going forward.

**Acceptance criteria**
Depends on:
https://github.com/elastisys/compliantkubernetes-apps/issues/666
https://github.com/elastisys/compliantkubernetes-apps/issues/668

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

### PR DESCRIPTION
**Pull request by OlleLarsson**
**What this PR does / why we need it**:
Upgrades the ingress-nginx helm chart to latest.
This bumps ingress-nginx to v1.x.x
This is needed as to support k8s >=1.22
The biggest change is the requirement of an ingressClass.

**Which issue this PR fixes**:
fixes #805  

**Public facing documentation PR**:

**Special notes for reviewer**:

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [x] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [ ] I upgraded no Chart.
    - [x] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

### CODE REVIEW

**Review by cristiklein — APPROVED** [review]
LGTM, but didn't test.

Should we update the [user demo Ingress](https://github.com/elastisys/compliantkubernetes/blob/main/user-demo/deploy/ck8s-user-demo/values.yaml#L37-L40) to specify an `ingressClass`?

**Comment by OlleLarsson** [comment]
> LGTM, but didn't test.
> 
> Should we update the [user demo Ingress](https://github.com/elastisys/compliantkubernetes/blob/main/user-demo/deploy/ck8s-user-demo/values.yaml#L37-L40) to specify an `ingressClass`?

I would say yes as the annotation is deprecated.

**Comment by cristiklein** [comment]
@OlleLarsson Your wish is my ticket. :smile:

**Review by Xartos — APPROVED** [review]
LGTM!

**Review by robinAwallace — APPROVED** [review]

**Pull request merged**
