### PR TITLE
config: Increase limits to reduce OOM alerts

### PR DESCRIPTION
**Pull request by lucianvlad**
> [!warning]
> **This is public repository, ensure not to disclose:**
> - [x] personal data beyond what is necessary for interacting with this pull request
> - [x] business confidential information, such as customer names

### What kind of PR is this?

**Required**: Mark one of the following that is applicable:

- [ ] kind/feature       
- [ ] kind/improvement   
- [ ] kind/deprecation   
- [ ] kind/documentation 
- [ ] kind/clean-up      
- [ ] kind/bug           
- [x] kind/other         

*Optional*: Mark one or more of the following that are applicable:

> [!important]
> Breaking changes should be marked `kind/admin-change` or `kind/dev-change` depending on type
> Critical security fixes should be marked with `kind/security`

- [ ] kind/admin-change  
- [ ] kind/dev-change    
- [ ] kind/security      
- [ ] [kind/adr]()       

### What does this PR do / why do we need this PR?

...

- Fixes #

#### Checklist

- [ ] Proper commit message prefix on all commits
  
- Change checks:
  - [ ] The change is transparent
  - [ ] The change is disruptive
  - [ ] The change requires no migration steps
  - [ ] The change requires migration steps
- Metrics checks:
  - [ ] The metrics are still exposed and present in Grafana after the change
  - [ ] The metrics names didn't change (Grafana dashboards and Prometheus alerts are not affected)
  - [ ] The metrics names did change (Grafana dashboards and Prometheus alerts were fixed)
- Logs checks:
  - [ ] The logs do not show any errors after the change
- Network Policy checks:
  - [ ] Any changed pod is covered by Network Policies
  - [ ] The change does not cause any dropped packages in the `NetworkPolicy Dashboard`
- Pod Security Policy checks:
  - [ ] Any changed pod is covered by Pod Security Admission
  - [ ] Any changed pod is covered by Gatekeeper Pod Security Policies
  - [ ] The change does not cause any pods to be blocked by Pod Security Admission or Policies
- Falco checks:
  - [ ] The change does not cause any alerts to be generated by Falco
- Audit checks:
  - [ ] The change does not cause any unnecessary Kubernetes audit events
  - [ ] The change requires changes to Kubernetes audit policy
- Bug checks:
  - [ ] The bug fix is covered by regression tests

### CODE REVIEW

**Comment by lucianvlad** [comment]
The migration script is to be created as part of  task #1952

**Comment by crssnd** [comment]
I think we should have a migration script to check and update the overwrite configs if the values are lower then the new defaults.

**Comment by lucianvlad** [comment]
> I think we should have a migration script to check and update the overwrite configs if the values are lower then the new defaults.

I tried to create it but I lack the YQ4 skills to do it
I pinged Andre and we both agreed that this script should be something that is needed not only for this migration but for future migrations also and be part of the prepare steps
So I opened a new issue for it [here](https://github.com/elastisys/compliantkubernetes-apps/issues/1952)

**Comment by crssnd** [comment]
> > I think we should have a migration script to check and update the overwrite configs if the values are lower then the new defaults.
> 
> I tried to create it but I lack the YQ4 skills to do it I pinged Andre and we both agreed that this script should be something that is needed not only for this migration but for future migrations also and be part of the prepare steps So I opened a new issue for it [here](https://github.com/elastisys/compliantkubernetes-apps/issues/1952)

yes I agree that with that task, but that will be completed at a later stage. 
I still think that we should have migration scripts for these changes, otherwise there is the risk of not applying them on the env.

**Comment by lucianvlad** [comment]
> > > I think we should have a migration script to check and update the overwrite configs if the values are lower then the new defaults.
> > 
> > 
> > I tried to create it but I lack the YQ4 skills to do it I pinged Andre and we both agreed that this script should be something that is needed not only for this migration but for future migrations also and be part of the prepare steps So I opened a new issue for it [here](https://github.com/elastisys/compliantkubernetes-apps/issues/1952)
> 
> yes I agree that with that task, but that will be completed at a later stage. I still think that we should have migration scripts for these changes, otherwise there is the risk of not applying them on the env.

I added the migration script.
Please review when you have the time
Thx

**Review by linus-astrom — APPROVED** [review]

**Pull request merged**
