### PR TITLE
Validate issuers email

### PR DESCRIPTION
**Pull request by cristiklein**
**What this PR does / why we need it**:

This PR adds validation for emails set to Issuers. Previously, setting an invalid email address lead to hard-to-find issues, like Certificates not becoming ready, because Issuers are not ready, because Issuer emails are incorrect. This PR makes the `apply` step fail. 

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #

**Public facing documentation PR** *(if applicable)*

N/A

**Special notes for reviewer**:

**Checklist:**

- [NA?] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [X] Proper commit message prefix on all commits
- [NA] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [X] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
Cool!
I'm not sure what to do about the unit tests though... Either we would have to provide a "valid" email by default, which doesn't feel right, or we need to change how we test. :thinking:

**Comment by OlleLarsson** [comment]
Is the only requirement that the mail address follows correct specification or does that mail address actaully need to exist?

**Comment by lentzi90** [comment]
I'm not sure. But I guess the real problem here is that we want to *both* help the user detect the problem by failing if they don't change the value, and run unit tests that detect problems with the charts. With the current way of testing this won't work, as any value that would pass the test would also be possible to install without the user changing it.

Maybe we could have some values for testing that are not just the defaults? Looks like we already [change some of them](https://github.com/elastisys/compliantkubernetes-apps/blob/main/pipeline/init-unit-tests.bash#L17).

**Comment by cristiklein** [comment]
@lentzi90 Excellent! That's the stuff I was looking for.

**Review by lentzi90 — APPROVED** [review]
LGTM!
I would not like too much logic in the `init-unit-test.bash` script though so if we need to add similar things for all the charts then I think it would be better to have a prepared config file instead of updating it in this way.

**Review by viktor-f — APPROVED** [review]
LGTM

**Comment by cristiklein** [comment]
> LGTM!
> I would not like too much logic in the `init-unit-test.bash` script though so if we need to add similar things for all the charts then I think it would be better to have a prepared config file instead of updating it in this way.

Agreed!

**Pull request merged**
