### PR TITLE
apps sc: Fixed influxdb retention disabled

### LINKED ISSUE #350: Disabling retention breaks influxDB
**Describe the bug**
In sc-config, it is possible to disable retention (influxdb.retention.enabled: false). However, this leads to a broken influxDB installation as a number of configmaps are not installed, while the container still tries to mount them on creation.

**To Reproduce**

Set influxdb.retention.enabled: false in sc-config for a new instatllation 
./bin/ck8s apply sc

Verify that influxdb-0 refuses to start

**Expected behavior**
Either it should be possible to deploy influxDB to a working state without retention or de option to disable it should be removed.

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version [e.g. v0.12.0] (and probably all earlier too)

**Additional context**

### PR DESCRIPTION
**Pull request by robinAwallace**
**What this PR does / why we need it**:

This fixes the problem when disabling retention for influxdb in sc-config breaks influxdb.

**Which issue this PR fixes**: 
fixes #350 

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [x] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [ ] I upgraded no Chart.
    - [x] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

### CODE REVIEW

**Comment by OlleLarsson** [comment]
InfluxDB is an elastisys chart and so I assume that changes are still to be made at [influxdb-helm-charts](https://github.com/elastisys/influxdb-helm-charts) -> [chart-repo](https://github.com/elastisys/chart-repo) -> compliantkubernetes-apps.

**Comment by robinAwallace** [comment]
> InfluxDB is an elastisys chart and so I assume that changes are still to be made at [influxdb-helm-charts](https://github.com/elastisys/influxdb-helm-charts) -> [chart-repo](https://github.com/elastisys/chart-repo) -> compliantkubernetes-apps.

**Comment by robinAwallace** [comment]
I have created pull requests in [influxdb-helm-charts](https://github.com/elastisys/influxdb-helm-charts/pull/11) and [chart-repo](https://github.com/elastisys/chart-repo/pull/14). Waiting for them to check that they work before i update this pull request.

**Comment by robinAwallace** [comment]
Updated the chart now. Please take another look.

**Review by OlleLarsson — APPROVED** [review]

**Review by Xartos — APPROVED** [review]
LGTM

**Pull request merged**
