### PR TITLE
Rework capacity management alerts and add dashboard

### LINKED ISSUE #1864: [5] Rework capacity alerts and create dashboard
**Is your feature request related to a problem? Please describe.**
We want to update our capacity alerts for cpu and memory based on a [recent investigation](https://github.com/elastisys/mse-internal-docs/blob/main/docs/investigations/capacity-alert-metrics/capacity-alert-metrics-investigation.md). 

**Describe the solution you'd like**
The capacity alerts should be reworked according to the suggestions in the investigation. As a summary, this is the suggested alerts (see the investigation for more details):

```
for cpu usage, memory usage
    for each node
        if average resource usage over 1 hour > ( 95% (cpu) or 85% (memory) )
            send alert and either redistribute pods across nodes or scale up
    for each node group
        if average resource usage over 1 hour > ( 95% (cpu) or 85% (memory) )
            send alert and scale up
        if average resource usage over 1 day > 75 %
            send alert and scale up
```

There should also be a grafana dashboard that shows the same metrics. It should serve as a way to give more context into how the resource usage has changed recently, both to give the platform administrators more knowledge and as evidence to show application developers for why a cluster needed to be scaled up. In the investigation there is a [start on a dashboard](https://github.com/elastisys/mse-internal-docs/blob/main/docs/investigations/capacity-alert-metrics/scaling-metrics-dashboard-testing.json) that can be used for inspiration.

In order to implement this, there should be a node label exposed for the node group in the metrics. The current suggestion would be `elastisys.io/node-group`, but the exact name can be discussed. It can be exposed like [this](https://github.com/elastisys/compliantkubernetes-apps/blob/0d7e99e80301a370bd61878553332e55aa54bb89/helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl#L67) (but for both sc and wc).

Lastly the [public documentation](https://github.com/elastisys/compliantkubernetes/blob/46c6e4359da7cfc6b4faeb3ed396a65060a0f0b4/docs/operator-manual/capacity-management.md) should also be updated to reflect the new policy.

**Describe alternatives you've considered**

**Additional context**

**Definition of done:**
- There are new capacity alerts based on the investigation
- There is a new grafana dashboard based on this
- The node group label is exposed to metrics
- Public documentation is updated

### PR DESCRIPTION
**Pull request by lunkan93**
> [!warning]
> **This is public repository, ensure not to disclose:**
> - [x] personal data beyond what is necessary for interacting with this pull request
> - [x] business confidential information, such as customer names

### What kind of PR is this?

**Required**: Mark one of the following that is applicable:

- [x] kind/feature       
- [ ] kind/improvement   
- [ ] kind/deprecation   
- [ ] kind/documentation 
- [ ] kind/clean-up      
- [ ] kind/bug           
- [ ] kind/other         

*Optional*: Mark one or more of the following that are applicable:

> [!important]
> Breaking changes should be marked `kind/admin-change` or `kind/dev-change` depending on type
> Critical security fixes should be marked with `kind/security`

- [x] kind/admin-change  
- [ ] kind/dev-change    
- [ ] kind/security      
- [ ] [kind/adr]()       

### Platform Administrator notice
Capacity management has been reworked with new alerts and a Grafana dashboard. In order for these to work, nodes must be labeled with `elastisys.io/node-group=<node-group>`.

### What does this PR do / why do we need this PR?

Adds capacity management alerts and a dashboard, based on our previous investigation regarding this.

- Fixes #1864 

#### Additional information to reviewers

- The alerts and dashboard will only account for nodes that have been labeled with `elastisys.io/node-group`.
  - This is checked per cluster, so you can use the same label, e.g. for control planes, in both clusters if you want.
- When migrating you will see duplicate entries for each node in the "Average per node over 1h"-panels of the dashboard due to the metric changes. This will go away after 2 hours.
  - I have not found any other negative side-effects caused by this.

#### Screenshots

Alert
Screenshot from 2024-02-05 14-40-32

Dashboard
Screenshot from 2024-02-05 14-42-09

Node Exporter dashboard for reference
Screenshot from 2024-02-05 14-41-47

Latest revision:

Screenshot from 2024-02-13 10-49-20

#### Checklist

- [x] Proper commit message prefix on all commits
  
- Change checks:
  - [ ] The change is transparent
  - [ ] The change is disruptive
  - [x] The change requires no migration steps
  - [ ] The change requires migration steps
- Metrics checks:
  - [x] The metrics are still exposed and present in Grafana after the change
  - [x] The metrics names didn't change (Grafana dashboards and Prometheus alerts are not affected)
  - [ ] The metrics names did change (Grafana dashboards and Prometheus alerts were fixed)
- Logs checks:
  - [x] The logs do not show any errors after the change
- Network Policy checks:
  - [ ] Any changed pod is covered by Network Policies
  - [ ] The change does not cause any dropped packages in the `NetworkPolicy Dashboard`
- Pod Security Policy checks:
  - [ ] Any changed pod is covered by Pod Security Admission
  - [ ] Any changed pod is covered by Gatekeeper Pod Security Policies
  - [ ] The change does not cause any pods to be blocked by Pod Security Admission or Policies
- Falco checks:
  - [ ] The change does not cause any alerts to be generated by Falco
- Audit checks:
  - [ ] The change does not cause any unnecessary Kubernetes audit events
  - [ ] The change requires changes to Kubernetes audit policy
- Bug checks:
  - [ ] The bug fix is covered by regression tests

### CODE REVIEW

**Review by Elias-elastisys — APPROVED** [review]
Nice, lgtm!

**Comment by anders-elastisys** [comment]
Do we add the `elastisys.io/node-group` label to the nodes somewhere? Should maybe adding the `elastisys.io/node-group` label be a `kind/admin-change` notice to make it clearer in the changelog that this label should be added to all nodes for these metric queries to work?

**Review by anders-elastisys — APPROVED** [review]

**Review by viktor-f — COMMENTED** [review]
Nice work!

I think it would make sense to remove/disable some of the old capacity alerts. Like [these ones](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile.d/charts/prometheus-alerts/templates/alerts/cluster-capacity-management-alerts.yaml#L45-L58) (there might be more).

I also think that the new values should be part of the [values file in the chart](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile.d/charts/prometheus-alerts/values.yaml).

**Review by viktor-f — APPROVED** [review]
You could add a screenshot of the latest changes to the dashboard for transparency. But it looks good to me.

Also remember to update the public docs

**Pull request merged**
