### PR TITLE
Fix Fluentd probe

### PR DESCRIPTION
**Pull request by Zash**
**What this PR does / why we need it**:

See screenshots and https://github.com/elastisys/compliantkubernetes-apps/pull/1542#issuecomment-1521382910

**Special notes for reviewer**:

Related to #1542 

**Add a screenshot or an example to illustrate the proposed solution:**

**Before**

image

**After**

image

Further investigation needed to find out whether the probe is correct about fluentd being down. Could also be more wrong with the probe URL.

**Checklist:**

- [ ] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [ ] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [ ] I upgraded no Chart.
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

### CODE REVIEW

**Review by aarnq — APPROVED** [review]

**Comment by Zash** [comment]
> Further investigation needed to find out whether the probe is correct about fluentd being down.

It's down, the probe is correct. Good to have that part of the dashboard tested :)

**Comment by Zash** [comment]
Furthermore, is Fluent running in the service cluster at all? It seems to be in the workload cluster, so a probe on the cluster-internal name from the *sc* seems unlikely to work. Finally, I'm not sure if the URL is even correct, running the same probe in the *wc* reports **DOWN** as well.

**Comment by aarnq** [comment]
> Furthermore, is Fluent running in the service cluster at all? It seems to be in the workload cluster, so a probe on the cluster-internal name from the _sc_ seems unlikely to work. Finally, I'm not sure if the URL is even correct, running the same probe in the _wc_ reports **DOWN** as well.

Yes, if you have fluentd enabled in the SC cluster and at least one of audit or scLogs enabled.

**Comment by Zash** [comment]
> Yes, if you have fluentd enabled in the SC cluster and at least one of audit or scLogs enabled.

Turns out I had (via defaults) `fluentd.enabled = false`...

**Review by crssnd — APPROVED** [review]

**Pull request merged**
