### PR TITLE
apps sc: upgrade opensearch 1.3.4

### LINKED ISSUE #977: [3]Upgrade to OpenSearch 1.3.x
**What Chart should be upgraded?**

[opensearch](https://github.com/elastisys/compliantkubernetes-apps/tree/main/helmfile/upstream/opensearch)

https://opensearch.org/blog/releases/2022/03/launch-announcement-1-3-0/

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [ ] We need to keep up to prevent future issues.
- [x] Other: To stay up-to-date and make the upgrade to 2.0 leaner.

**Acceptance criteria**

- I checked the migration of the new Chart:
    - [x] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [x] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

### PR DESCRIPTION
**Pull request by davidumea**
**What this PR does / why we need it**:

Upgraded opensearch chart to `1.13.1` which upgrades opensearch to `1.3.4`
Upgraded opensearch-dashboards chart to `1.7.4` which upgrades opensearch-dashboards to `1.3.4`

**Which issue this PR fixes** : fixes #977

**Special notes for reviewer**:

**Checklist:**

- [X] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [X] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [X] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [ ] I upgraded no Chart.
    - [X] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

### CODE REVIEW

**Comment by davidumea** [comment]
[this cluster](https://opensearch.david.dev-ck8s.com) has this version of opensearch/opensearch-dashboards applied, you can test some of the [new features](https://opensearch.org/blog/releases/2022/03/launch-announcement-1-3-0/) there if you'd like.

**Review by robinAwallace — COMMENTED** [review]
LGTM. Have you testade to migrate a cluster? If no please do that :slightly_smiling_face:

**Comment by davidumea** [comment]
> LGTM. Have you testade to migrate a cluster? If no please do that slightly_smiling_face

The cluster is on apps `v0.24.1` so I made a local branch based on `v0.24.1` with these changes and applied helmfile -l group=opensearch, is this what you mean by migrated?

**Review by robinAwallace — APPROVED** [review]

**Review by crssnd — APPROVED** [review]
tested on my dev cluster and looks ok

are there any important changes that should be added in the Changelog?

**Review by lucianvlad — APPROVED** [review]
LGTM

**Comment by davidumea** [comment]
> are there any important changes that should be added in the Changelog?

Nothing huge but I added an extra comment in the changelog linking to their launch announcement.

**Pull request merged**
