### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by aarnq**
Additionally use form templates

> [!warning]
> **This is public repository, ensure not to disclose:**
> - [x] personal data beyond what is necessary for interacting with this pull request
> - [x] business confidential information, such as customer names

### What kind of PR is this?

**Required**: Mark one of the following that is applicable:

- [ ] kind/feature       
- [ ] kind/improvement   
- [ ] kind/deprecation   
- [x] kind/documentation 
- [ ] kind/clean-up      
- [ ] kind/bug           
- [ ] kind/other         

*Optional*: Mark one or more of the following that are applicable:

> [!important]
> Breaking changes should be marked `kind/admin-change` or `kind/dev-change` depending on type
> Critical security fixes should be marked with `kind/security`

- [ ] kind/admin-change  
- [ ] kind/dev-change    
- [ ] kind/security      
- [ ] [kind/adr]()       

### What does this PR do / why do we need this PR?

Updates the issue templates slightly and makes them more structured.
(This will later be pushed out to other repositories.)

The really biggest change is to merge the proposed feature and proposed solution on feature request into one, since it is usually easier to express the what and the why in that manner.

#### Additional information to reviewers

Go to [here](https://github.com/elastisys/compliantkubernetes-apps/tree/aarnq/update-issue-templates/.github/ISSUE_TEMPLATE) and you can click on each to see how they render.

Might do a touch up on the PR template in this PR as well.

#### Checklist

- [x] Proper commit message prefix on all commits
  
- Change checks:
  - [x] The change is transparent
  - [ ] The change is disruptive
  - [x] The change requires no migration steps
  - [ ] The change requires migration steps
- Metrics checks:
  - [ ] The metrics are still exposed and present in Grafana after the change
  - [ ] The metrics names didn't change (Grafana dashboards and Prometheus alerts are not affected)
  - [ ] The metrics names did change (Grafana dashboards and Prometheus alerts were fixed)
- Logs checks:
  - [ ] The logs do not show any errors after the change
- Network Policy checks:
  - [ ] Any changed pod is covered by Network Policies
  - [ ] The change does not cause any dropped packages in the `NetworkPolicy Dashboard`
- Pod Security Policy checks:
  - [ ] Any changed pod is covered by Pod Security Admission
  - [ ] Any changed pod is covered by Gatekeeper Pod Security Policies
  - [ ] The change does not cause any pods to be blocked by Pod Security Admission or Policies
- Falco checks:
  - [ ] The change does not cause any alerts to be generated by Falco
- Audit checks:
  - [ ] The change does not cause any unnecessary Kubernetes audit events
  - [ ] The change requires changes to Kubernetes audit policy
- Bug checks:
  - [ ] The bug fix is covered by regression tests

### CODE REVIEW

**Comment by robinAwallace** [comment]
Can you show us the result (screenshots) of these changes? :slightly_smiling_face:

**Comment by aarnq** [comment]
> ~Can you show us the result (screenshots) of these changes? 🙂~ Nvm i saw the link 😅

I've updated the link, it pointed to the wrong branch :sweat_smile:

**Comment by robinAwallace** [comment]
Chart upgrade seems to have a issue :thinking: 
image

In general I like it :+1: 
Im thinking that there should also be a "problem" issue or that bug should incorporate general problems. What do you think about that? :slightly_smiling_face:

**Review by robinAwallace — APPROVED** [review]
My comment should not be seen as a blocker :slightly_smiling_face:

**Review by crssnd — APPROVED** [review]

**Review by lunkan93 — APPROVED** [review]

**Review by lucianvlad — APPROVED** [review]

**Pull request merged**
