### PR TITLE
apps: upgrade velero to v2.27.3 and velero to v1.7.1

### LINKED ISSUE #666: [3] Upgrade velero to v1.7.0
**What Chart should be upgraded?**
upstream / velero: [vmware-tanzu/velero](https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero)
v1.5.3/v2.15.0 (2021/03/05) -> v1.7.0/v2.26.2 (2021/10/27)

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

Need to upgrade this for it to support APIs on K8s v1.22 going forward.

Also fixes a potential issue where restic might fail to successfully perform restores on K8s v1.21.

**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

### PR DESCRIPTION
**Pull request by Pavan-Gunda**
**What this PR does / why we need it**:
This PR upgrades velero helm chart to 2.27.3 
**Which issue this PR fixes** : fixes #666

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [ ] I upgraded no Chart.
    - [x] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

### CODE REVIEW

**Review by Xartos — APPROVED** [review]
LGTM

**Review by robinAwallace — COMMENTED** [review]
LGTM. However would be good to show in the PR that velero works by showing the result of a backup and restore.

**Comment by Pavan-Gunda** [comment]
Screenshot from 2022-02-14 08-49-20
Screenshot from 2022-02-14 08-54-09
Screenshot from 2022-02-14 08-51-53

**Comment by Pavan-Gunda** [comment]
will these do? 

it is a dev cluster running velero v1.7.1

**Review by robinAwallace — APPROVED** [review]

**Pull request merged**
