### PR TITLE
apps: separate the ops and user grafana dashboards

### LINKED ISSUE #12: [3] Users elasticsearch dashboard in grafana shows errors and no data
The elasticsearch dashboard in the user grafana is empty and shows errors about the datasource. I think this dashboard should not be available to the user. It should only be in the Ops grafana.

### PR DESCRIPTION
**Pull request by crssnd**
**What this PR does / why we need it**: it will allow us to control what grafana dashboards from the grafana-ops chart will be visible to the user

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #12 

**Special notes for reviewer**:
1. only dashboards with "labelKey" values set to 1 will be visible to the user. By default all kube-prometheus-stack dashboards. An ops dashboard can be visible to the user if you set "user_visible" to true in grafana-ops/values.yaml
2. the grafana-ops chart template was modified to automatically load the dashboards defined in the values.yaml file
3. we will have one ConfigMap for each dashboard
4. added the prometheus-sc datasource in user-grafana so they will have access to all metrics.

Before:
grafana-user-before

After: 
grafana-user-after

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [x] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [ ] I upgraded no Chart.
    - [x] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

### CODE REVIEW

**Review by Xartos — COMMENTED** [review]
Looking really good, nice work!
Although would it be possible to set labelValue to `user` instead of `1`? Seems a bit more descriptive.

**Comment by crssnd** [comment]
> Looking really good, nice work!
> Although would it be possible to set labelValue to `user` instead of `1`? Seems a bit more descriptive.

unfortunately not really possible. 
I used "1" because this is the value hardcoded in [kube-prometheus-stack dashboards](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/configmap-dashboards.yaml). 
This way they will see this dashboards by default.

**Comment by Xartos** [comment]
> > Looking really good, nice work!
> > Although would it be possible to set labelValue to `user` instead of `1`? Seems a bit more descriptive.
> 
> unfortunately not really possible.
> I used "1" because this is the value hardcoded in [kube-prometheus-stack dashboards](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/configmap-dashboards.yaml).
> This way they will see this dashboards by default.

Right, well then it makes sense.

**Review by Xartos — APPROVED** [review]

**Review by viktor-f — COMMENTED** [review]
Looks nice!
I just want to note that with this we are giving the users access to all metrics from the service cluster, since we often (sometimes?) give users editor access in grafana. Then they can use whatever metrics they want.
I'm ok with this, but just want to make sure that others are also ok with it.

**Comment by crssnd** [comment]
> Looks nice!
> I just want to note that with this we are giving the users access to all metrics from the service cluster, since we often (sometimes?) give users editor access in grafana. Then they can use whatever metrics they want.
> I'm ok with this, but just want to make sure that others are also ok with it.

We discussed it in an arch meeting and I also highlighted it in the issue [#12](https://github.com/elastisys/compliantkubernetes-apps/issues/12). If needed I can ask for a confirmation.

**Review by viktor-f — APPROVED** [review]

**Pull request merged**
