### PR TITLE
Upgrade Grafana chart to v8.4.7 and image to v11.1.4

### LINKED ISSUE #2167: [2] Upgrade Grafana
### Chart to upgrade

https://github.com/grafana/helm-charts/releases

### Reason for upgrade

- [ ] Security patching
- [ ] Upgrade to allow new features
- [X] Upgrade to prevent future issues
- [ ] Upgrade to maintain a supported version
- [ ] Other - _Write the reason below_

### Additional context

_No response_

### Acceptance criteria

- I checked the migration of the new chart version:
  - [ ] The upgrade does not require migration steps
  - [ ] The upgrade requires migration steps
- I tested the functionality of the new chart version:
  - [ ] The upgrade does not change current functionality
  - [ ] The upgrade changes current functionality

### PR DESCRIPTION
**Pull request by anders-elastisys**
> [!warning]
> **This is a public repository, ensure not to disclose:**
>
> - [x] personal data beyond what is necessary for interacting with this pull request, nor
> - [x] business confidential information, such as customer names.

### What kind of PR is this?

**Required**: Mark one of the following that is applicable:

- [ ] kind/feature       
- [x] kind/improvement   
- [ ] kind/deprecation   
- [ ] kind/documentation 
- [ ] kind/clean-up      
- [ ] kind/bug           
- [ ] kind/other         

*Optional*: Mark one or more of the following that are applicable:

> [!important]
> Breaking changes should be marked `kind/admin-change` or `kind/dev-change` depending on type
> Critical security fixes should be marked with `kind/security`

- [ ] kind/admin-change 
- [x] kind/dev-change   
- [ ] kind/security     
- [ ] [kind/adr]()      

### Application Developer notice

Angular plugins for Grafana dashboards are no longer supported by default. Please migrate any dashboards that contain panels that use Angular plugins (see [here](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/) for more information).

### What does this PR do / why do we need this PR?

Upgrades Grafana chart to v8.4.7 and Grafana image to v11.1.4, removing the previous override for setting the image version.

- Fixes #2167 

#### Checklist

- [x] Proper commit message prefix on all commits
  
- Change checks:
  - [ ] The change is transparent
  - [ ] The change is disruptive
  - [x] The change requires no migration steps
  - [ ] The change requires migration steps
  - [ ] The change upgrades CRDs
  - [ ] The change updates the config *and* the schema
- Metrics checks:
  - [x] The metrics are still exposed and present in Grafana after the change
  - [ ] The metrics names didn't change (Grafana dashboards and Prometheus alerts are not affected)
  - [ ] The metrics names did change (Grafana dashboards and Prometheus alerts were fixed)
- Logs checks:
  - [x] The logs do not show any errors after the change
- Pod Security Policy checks:
  - [ ] Any changed pod is covered by Pod Security Admission
  - [ ] Any changed pod is covered by Gatekeeper Pod Security Policies
  - [ ] The change does not cause any pods to be blocked by Pod Security Admission or Policies
- Network Policy checks:
  - [ ] Any changed pod is covered by Network Policies
  - [x] The change does not cause any dropped packets in the `NetworkPolicy Dashboard`
- Audit checks:
  - [ ] The change does not cause any unnecessary Kubernetes audit events
  - [ ] The change requires changes to Kubernetes audit policy
- Falco checks:
  - [x] The change does not cause any alerts to be generated by Falco
- Bug checks:
  - [ ] The bug fix is covered by regression tests

### CODE REVIEW

**Review by OlleLarsson — APPROVED** [review]
LGTM!

**Review by aarnq — COMMENTED** [review]
Does it pass the Grafana end-to-end tests?

**Comment by anders-elastisys** [comment]
> Does it pass the Grafana end-to-end tests?

I just tested running `make run-end-to-end/grafana` with this version and all tests passed:

```console
✗ make run-end-to-end/grafana
--- run end-to-end/grafana
1..28
# cypress run: /home/anders/ck8s/compliantkubernetes-apps/tests/end-to-end/grafana/authentication.cy.js
ok 1 grafana admin authentication can login via static admin user
ok 2 grafana admin authentication can login via static dex user # skip cypress skipped this test
ok 3 grafana dev authentication can login via static admin user
ok 4 grafana dev authentication can login via static dex user # skip cypress skipped this test
ok 5 grafana admin can discover dashboards
ok 6 grafana admin can load dashboards without error
ok 7 grafana dev can discover dashboards
ok 8 grafana dev can load dashboards without error
# cypress run: /home/anders/ck8s/compliantkubernetes-apps/tests/end-to-end/grafana/dashboards.cy.js
ok 9 grafana admin dashboards open the Backup status dashboard # skip cypress skipped this test
ok 10 grafana admin dashboards open the Trivy Operator Dashboard # skip cypress skipped this test
ok 11 grafana admin dashboards open the NetworkPolicy Dashboard # skip cypress skipped this test
ok 12 grafana admin dashboards open the Kubernetes cluster status dashboard # skip cypress skipped this test
ok 13 grafana admin dashboards open the Gatekeeper dashboard # skip cypress skipped this test
ok 14 grafana admin dashboards open the NGINX Ingress controller dashboard # skip cypress skipped this test
ok 15 grafana admin dashboards open the Falco dashboard # skip cypress skipped this test
ok 16 grafana dev dashboards   //open the Backup status dashboard # skip cypress skipped this test
ok 17 grafana dev dashboards open the Trivy Operator Dashboard # skip cypress skipped this test
ok 18 grafana dev dashboards open the NetworkPolicy Dashboard # skip cypress skipped this test
ok 19 grafana dev dashboards open the Kubernetes cluster status dashboard # skip cypress skipped this test
ok 20 grafana dev dashboards open the Gatekeeper dashboard # skip cypress skipped this test
ok 21 grafana dev dashboards open the NGINX Ingress controller dashboard # skip cypress skipped this test
ok 22 grafana dev dashboards open the Falco dashboard # skip cypress skipped this test
# cypress run: /home/anders/ck8s/compliantkubernetes-apps/tests/end-to-end/grafana/datasources.cy.js
ok 23 grafana admin datasources has prometheus # skip cypress skipped this test
ok 24 grafana admin datasources has thanos all # skip cypress skipped this test
ok 25 grafana admin datasources has thanos sc # skip cypress skipped this test
ok 26 grafana admin datasources has thanos wc # skip cypress skipped this test
ok 27 grafana dev datasources has service cluster # skip cypress skipped this test
ok 28 grafana dev datasources has workload cluster # skip cypress skipped this test
```

**Review by robinelastisys — APPROVED** [review]
Well done! :+1:

**Comment by anders-elastisys** [comment]
I noticed that one of the new changes with the Helm chart causes a diff everytime for the PVC:
```diff
monitoring, user-grafana, PersistentVolumeClaim (v1) has changed:
  # Source: grafana/templates/pvc.yaml
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: user-grafana
    namespace: monitoring
-   volumeName: pvc-b2b2459e-ed38-4e9c-bb2e-5bf316d0ee3c
```
This seems to be caused by [this change](https://github.com/grafana/helm-charts/pull/3041), we should be able to disable this behavior by setting the new [.persistence.lookupVolumeName](https://github.com/grafana/helm-charts/pull/3163) variable to false, but that needs to be done before migrating to the new helm chart. Having the diff each time does not seem to cause any issues, but it might become confusing. Any thoughts on this?

**Comment by anders-elastisys** [comment]
> > I noticed that one of the new changes with the Helm chart causes a diff everytime for the PVC after having upgraded to the new chart version:
> > ```diff
> > monitoring, user-grafana, PersistentVolumeClaim (v1) has changed:
> >   # Source: grafana/templates/pvc.yaml
> >   apiVersion: v1
> >   kind: PersistentVolumeClaim
> >   metadata:
> >     name: user-grafana
> >     namespace: monitoring
> > -   volumeName: pvc-b2b2459e-ed38-4e9c-bb2e-5bf316d0ee3c
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This seems to be caused by [this change](https://github.com/grafana/helm-charts/pull/3041), we should be able to disable this behavior by setting the new [.persistence.lookupVolumeName](https://github.com/grafana/helm-charts/pull/3163) variable to false, but that needs to be done before migrating to the new helm chart. Having the diff each time does not seem to cause any issues, but it might become confusing. Any thoughts on this?
> 
> IMO, we should try to avoid "false-diffs" if we can.

I fixed it to not show false diffs https://github.com/elastisys/compliantkubernetes-apps/pull/2245/commits/9915045ad9c5bb28ae0284958e54a9036ab86792

**Review by Zash — APPROVED** [review]
LGTM!

**Pull request merged**
