### PR TITLE
Patch 0.31.2

### PR DESCRIPTION
**Pull request by crssnd**
**What this PR does / why we need it**: fix for apps

### CODE REVIEW

**Review by Pavan-Gunda — APPROVED** [review]

**Comment by Pavan-Gunda** [comment]
https://github.com/elastisys/compliantkubernetes-apps/commit/5b49c0fb4ebcfb968418dc288833998b67aaceb1

Do we want to include this ?

**Comment by crssnd** [comment]
> [5b49c0f](https://github.com/elastisys/compliantkubernetes-apps/commit/5b49c0fb4ebcfb968418dc288833998b67aaceb1)
> 
> Do we want to include this ?

not sure. As far as I know that fix is only for Safari

**Comment by OlleLarsson** [comment]
> [5b49c0f](https://github.com/elastisys/compliantkubernetes-apps/commit/5b49c0fb4ebcfb968418dc288833998b67aaceb1)
> 
> Do we want to include this ?

It should be possible to configure on a case-by-case basis with [this](https://github.com/elastisys/compliantkubernetes-apps/commit/22a268069ee8f6cc99357746ee66690d4afe4c44)

**Comment by crssnd** [comment]
> > [5b49c0f](https://github.com/elastisys/compliantkubernetes-apps/commit/5b49c0fb4ebcfb968418dc288833998b67aaceb1)
> > Do we want to include this ?
> 
> It should be possible to configure on a case-by-case basis with [this](https://github.com/elastisys/compliantkubernetes-apps/commit/22a268069ee8f6cc99357746ee66690d4afe4c44)

but do we want this in the patch? I feel like it's too big of a feature for a patch release

**Comment by OlleLarsson** [comment]
> > > [5b49c0f](https://github.com/elastisys/compliantkubernetes-apps/commit/5b49c0fb4ebcfb968418dc288833998b67aaceb1)
> > > Do we want to include this ?
> > 
> > 
> > It should be possible to configure on a case-by-case basis with [this](https://github.com/elastisys/compliantkubernetes-apps/commit/22a268069ee8f6cc99357746ee66690d4afe4c44)
> 
> but do we want this in the patch? I feel like it's too big of a feature for a patch release

Sorry I thought this was for 0.32.1

**Review by OlleLarsson — APPROVED** [review]

**Pull request merged**
