### PR TITLE
Dex update

### LINKED ISSUE #193: [3] Release 0.10.0
Fork from master, QA/bugfixing and create the release 0.10.0 

Included tasks: 
- Document bug fixes: 1 day
- Automate Harbor + OPA checks: 1 day
- Upgrading apps: 1 day

### PR DESCRIPTION
**Pull request by geoff-elastisys**
**What this PR does / why we need it**: Updates dex application and chart

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #193

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [ ] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.

### CODE REVIEW

**Review by OlleLarsson — COMMENTED** [review]
The changes looks OK, I did try and upgrade and it seemd to have worked.
I did not test any functionalty though, so could just just run some small checks and confirm that OIDC still works?

**Comment by geoff-elastisys** [comment]
> The changes looks OK, I did try and upgrade and it seemd to have worked.
> I did not test any functionalty though, so could just just run some small checks and confirm that OIDC still works?

Well do

**Comment by geoff-elastisys** [comment]
OIDC: created a user called Geoff and assigned roles of kibana_user and kubernetes_log_reader
image
image

**Comment by geoff-elastisys** [comment]
Dex: Can log in as expected from set domain (elastisys.com)

**Review by OlleLarsson — APPROVED** [review]

**Review by viktor-f — APPROVED** [review]
LGTM (have not tested)

**Pull request merged**
