### PR TITLE
apps sc & wc: cert-manager upgraded from 1.1.0 to 1.4.0

### LINKED ISSUE #273: Upgrade cert-manager to 1.4
**Is your feature request related to a problem?**
v1.2 of cert-manager has been released.
https://github.com/jetstack/cert-manager/releases/tag/v1.2.0

**Describe the solution you'd like**
That we'd upgrade to this version to get the latest of features.

**Describe alternatives you've considered**
None.

**Additional context**

**Definition of done:**
- Cert-manager helm chart upgraded to version that's running 1.12 by default.
- Our cert-manager resources upgraded to adhere to any api changes in the new version.

### PR DESCRIPTION
**Pull request by robinelastisys**
**What this PR does / why we need it**:
cert-manager chart upgrade from 1.1.0 to 1.4.0.

**Which issue this PR fixes**:
fixes #273 

**Special notes for reviewer**:
No migration steps needed if "installCRDs: true"

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [x] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [ ] I upgraded no Chart.
    - [x] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

### CODE REVIEW

**Review by viktor-f — COMMENTED** [review]
If we now run as non-root on all cert-manager containers then we can remove the PSP RBAC set up for cert-manager https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/common-psp-rbac/templates/cert-manager-psp-rbac.yaml

I'd like to have it in this PR but it might not be critical

**Review by Xartos — APPROVED** [review]
LGTM

**Review by viktor-f — APPROVED** [review]

**Comment by OlleLarsson** [comment]
Don't we need a way of upgrading the CRDs or does Cert-manager handle them differently?

**Comment by viktor-f** [comment]
> Don't we need a way of upgrading the CRDs or does Cert-manager handle them differently?

According to the PR description:

> No migration steps needed if "installCRDs: true"

**Pull request merged**
