### PR TITLE
Move restore instructions and resources to /restore

### PR DESCRIPTION
**Pull request by simonklb**
> [!warning]
> **This is a public repository, ensure not to disclose:**
>
> - [ ] personal data beyond what is necessary for interacting with this pull request, nor
> - [ ] business confidential information, such as customer names.

### What kind of PR is this?

**Required**: Mark one of the following that is applicable:

- [ ] kind/feature       
- [ ] kind/improvement   
- [ ] kind/deprecation   
- [ ] kind/documentation 
- [x] kind/clean-up      
- [ ] kind/bug           
- [ ] kind/other         

*Optional*: Mark one or more of the following that are applicable:

> [!important]
> Breaking changes should be marked `kind/admin-change` or `kind/dev-change` depending on type
> Critical security fixes should be marked with `kind/security`

- [ ] kind/admin-change 
- [ ] kind/dev-change   
- [ ] kind/security     
- [ ] [kind/adr]()      

### What does this PR do / why do we need this PR?

The resources related to restore were spread out in the repository, this collects them in a single place.

Neither /docs nor /scripts felt correct, that's why we put them under a new root directory. If we, in the future, create restore scripts it could make sense to move the scripts under /scripts and the instructions to /docs.

#### Checklist

- [x] Proper commit message prefix on all commits
  
- Change checks:
  - [ ] The change is transparent
  - [ ] The change is disruptive
  - [ ] The change requires no migration steps
  - [ ] The change requires migration steps
  - [ ] The change upgrades CRDs
  - [ ] The change updates the config *and* the schema
- Documentation checks:
  - [ ] The [public documentation](https://github.com/elastisys/compliantkubernetes) required no updates
  - [x] The [public documentation](https://github.com/elastisys/compliantkubernetes) required an update - [link to change](https://github.com/elastisys/compliantkubernetes/pull/973)
- Metrics checks:
  - [ ] The metrics are still exposed and present in Grafana after the change
  - [ ] The metrics names didn't change (Grafana dashboards and Prometheus alerts are not affected)
  - [ ] The metrics names did change (Grafana dashboards and Prometheus alerts were fixed)
- Logs checks:
  - [ ] The logs do not show any errors after the change
- Pod Security Policy checks:
  - [ ] Any changed pod is covered by Pod Security Admission
  - [ ] Any changed pod is covered by Gatekeeper Pod Security Policies
  - [ ] The change does not cause any pods to be blocked by Pod Security Admission or Policies
- Network Policy checks:
  - [ ] Any changed pod is covered by Network Policies
  - [ ] The change does not cause any dropped packets in the `NetworkPolicy Dashboard`
- Audit checks:
  - [ ] The change does not cause any unnecessary Kubernetes audit events
  - [ ] The change requires changes to Kubernetes audit policy
- Falco checks:
  - [ ] The change does not cause any alerts to be generated by Falco
- Bug checks:
  - [ ] The bug fix is covered by regression tests

### CODE REVIEW

**Comment by Zash** [comment]
Should this be marked an admin change, perhaps?

**Comment by simonklb** [comment]
> Should this be marked an admin change, perhaps?

To me it doesn't feel noteworthy enough but if you or someone else insist I'll add an admin notice!

**Comment by aarnq** [comment]
I hope any and all internal and public documentation is updated to point to the moved files?

**Comment by Zash** [comment]
Looks like these two will need updating:

https://github.com/elastisys/compliantkubernetes/blob/945c36e8f859ce8c57fcea6a151fa59655ec008e/docs/operator-manual/disaster-recovery.md#L35

https://github.com/elastisys/compliantkubernetes/blob/945c36e8f859ce8c57fcea6a151fa59655ec008e/docs/operator-manual/disaster-recovery.md#L306

**Review by Zash — APPROVED** [review]

**Review by aarnq — DISMISSED** [review]

**Comment by aarnq** [comment]
The harbor readme needs to have paths updated as part of this.

**Comment by Zash** [comment]
Maybe this one as well

https://github.com/elastisys/compliantkubernetes-apps/blob/83f21bf64006390d5bcc3b3e77e9227d9f3bb92d/migration/v0.25.x-v0.26.x/upgrade-apps.md#L118

**Comment by simonklb** [comment]
> Maybe this one as well
> 
> https://github.com/elastisys/compliantkubernetes-apps/blob/83f21bf64006390d5bcc3b3e77e9227d9f3bb92d/migration/v0.25.x-v0.26.x/upgrade-apps.md#L118

I don't think so since that would be the correct path for that version. However, the migration directory could probably be cleaned up a bit. I don't expect anyone running v0.25 at this point. :smile:

**Review by anders-elastisys — APPROVED** [review]

**Pull request merged**
