### PR TITLE
Fix user Grafana Deployment

### PR DESCRIPTION
**Pull request by cristiklein**
**What this PR does / why we need it**:

Set deploymentStrategy to Recreate for user Grafana, so that upgrades
work. A rollingUpdate strategy fails, due to persistence being set to
ReadWriteOnce.

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #

Treat this as a temporary fix for #185. A permanent fix will likely come
with #242.

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [X] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [X] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [X] minor downtime of user Grafana is expected.
    - [ ] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]
LGTM!

**Review by OlleLarsson — APPROVED** [review]

**Comment by viktor-f** [comment]
It seems like I'm a bit late. But this will make grafana create a new PV when it creates a new pod, right?
In that case you would lose all user data that has been added. Primarily dashboards that the users have added and any manual changes to permissions that we have done. I don't think that is what we should go for. But I don't really have a better fix for it right now other than that you can delete the old pod during any upgrade, then the new pod can mount the PV.

**Comment by cristiklein** [comment]
@viktor-f The newly created Pod should attach to the existing PV with zero data loss. Why would you suspect that a new PV is created?

**Comment by viktor-f** [comment]
My bad, didn't read properly. Though it was the PVC policy that was changed not deploymentStrategy. So just ignore what I said :smile:

**Pull request merged**
