### PR TITLE
apps: Install podsecuritypolicies per stack

### PR DESCRIPTION
**Pull request by aarnq**
**What this PR does / why we need it**:

Since it will simplify a lot of things and will be a requirement to move forward with advanced rollbacks during upgrades.

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [ ] I upgraded no Chart.
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

### CODE REVIEW

**Comment by OlleLarsson** [comment]
So with this one would do something like this to apply the default mutations to user namespaces?

```
# PSP helmfile 
- name: podsecuritypolicy
  namespace: gatekeeper-system
  labels:
    psp: user-restricted
  chart: ./charts/gatekeeper/podsecuritypolicies
  version: 0.1.0
  values:
    - values/podsecuritypolicies/common/user-restricted.yaml.gotmpl

  # helmfile/values/psp/common/user-restricted.yaml.gotmpl
  mutations:
    namespaceSelectorLabels:
      - key: owner
        operator: NotIn
        values:
          - operator
```

**Comment by aarnq** [comment]
> So with this one would do something like this to apply the default mutations to user namespaces?
> ...

Yes, that is the idea.

**Comment by aarnq** [comment]
We also could just install the restricted constraints with the namespaceSelectorLabels as they will just act as an additional barrier.

**Review by OlleLarsson — APPROVED** [review]
Looks OK from what I have tested.
I had to increase the memory limit on gatekeeper pods as it seemed  like it couldn't initially handle  all of the additional costrainttemplates

**Review by crssnd — APPROVED** [review]
same resource issue as Olle. this increase worked for me:
```
opa:
  controllerManager:
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 150Mi

```

**Comment by aarnq** [comment]
I'll merge this after the dependent PR is merged #1545 The resources for controller have been increased there.

**Review by robinAwallace — APPROVED** [review]

**Pull request merged**
